### ISSUE TITLE
CocoaMQTT does not work with moquette and HiveMQ on IOS

### ISSUE THREAD

**Issue by pabloa** [emqtt/CocoaMQTT#19]
Hello

It seems like CocoaMQTT does not send standard messages. I tested it with 2 mqtt brokers and I got the some no response. Here it is what I did.

I wrote this code (that is basically the same code in main.swift):

```javascript
    let mqtthost = "10.0.0.10" // the ip address of the mqtt broker.
    let mqttCli = CocoaMQTTCli()
    let clientIdPid = "CocoaMQTT-" + String(NSProcessInfo().processIdentifier)
    let mqtthost = "24.25.1.31"
    let mqtt = CocoaMQTT(clientId: clientIdPid, host: mqtthost, port: 1883)
//    mqtt.username = "test"
//    mqtt.password = "public"
    mqtt.willMessage = CocoaMQTTWill(topic: "/will", message: "dieout")
    mqtt.keepAlive = 90
    mqtt.delegate = mqttCli
    let connected = mqtt.connect()
    NSLog("Connected \(connected)")
    mqtt.subscribe("/a/b/c", qos: CocoaMQTTQOS.QOS1)
    mqtt.publish("/a/b/c", withString: "Qos0 Msg", qos: CocoaMQTTQOS.QOS0)
    mqtt.publish("/a/b/c", withString: "Qos1 Msg", qos: CocoaMQTTQOS.QOS1)
    mqtt.publish("/a/b/c", withString: "Qos2 Msg", qos: CocoaMQTTQOS.QOS2)
    mqtt.ping()
```

Client console output is:
```text
Hello, CocoaMQTT!
2015-10-18 13:21:36.075 thought you[20155:1236000] Connected true
didPublishMessage to /a/b/c
didPing
```

The IOS application never receives messages. It could send but they are never published. I launched a moquette broker instance on localhost. Here is mqtt output:

```text
                                                                         
  ___  ___                       _   _        ___  ________ _____ _____  
  |  \/  |                      | | | |       |  \/  |  _  |_   _|_   _| 
  | .  . | ___   __ _ _   _  ___| |_| |_ ___  | .  . | | | | | |   | |   
  | |\/| |/ _ \ / _\ | | | |/ _ \ __| __/ _ \ | |\/| | | | | | |   | |   
  | |  | | (_) | (_| | |_| |  __/ |_| ||  __/ | |  | \ \/' / | |   | |   
  \_|  |_/\___/ \__, |\__,_|\___|\__|\__\___| \_|  |_/\_/\_\ \_/   \_/   
                   | |                                                   
                   |_|                                                   
                                                                         
0    [main] INFO  Server  - Using config file: /Users/pablo/Downloads/distribution-0.7-bundle-tar/config/moquette.conf
5    [main] INFO  Server  - Persistent store file: /Users/pablo/Downloads/distribution-0.7-bundle-tar/bin/moquette_store.mapdb
174  [main] INFO  FileAuthenticator  - Loading password file: /Users/pablo/Downloads/distribution-0.7-bundle-tar/config/password_file.conf
405  [main] INFO  NettyAcceptor  - Server binded host: 0.0.0.0, port: 1883
408  [main] INFO  NettyAcceptor  - Server binded host: 0.0.0.0, port: 8080
Server started, version 0.7
7401 [nioEventLoopGroup-3-1] INFO  NettyMQTTHandler  - Received a message of type SUBSCRIBE
7402 [nioEventLoopGroup-3-1] INFO  NettyMQTTHandler  - Received a message of type PUBLISH
7402 [nioEventLoopGroup-3-1] INFO  NettyMQTTHandler  - Received a message of type PUBLISH
7402 [nioEventLoopGroup-3-1] INFO  NettyMQTTHandler  - Received a message of type PUBLISH
7403 [pool-1-thread-1] ERROR SimpleMessaging  - Serious error processing the message org.eclipse.moquette.proto.messages.SubscribeMessage@7517ce04 for session [clientID: null]org.eclipse.moquette.server.netty.NettyChannel@30155ec2
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:66)
	at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:173)
	at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:62)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:64)
	... 6 more
Caused by: java.lang.NullPointerException
	at org.eclipse.moquette.spi.impl.ProtocolProcessor.processSubscribe(ProtocolProcessor.java:606)
	... 11 more
7412 [pool-1-thread-1] INFO  ProtocolProcessor  - PUBLISH from clientID <null> on topic </a/b/c> with QoS MOST_ONE
7413 [pool-1-thread-1] INFO  ProtocolProcessor  - PUBLISH from clientID <null> on topic </a/b/c> with QoS LEAST_ONE
7406 [nioEventLoopGroup-3-1] INFO  NettyMQTTHandler  - Received a message of type PINGREQ
7424 [nioEventLoopGroup-3-1] INFO  NettyMQTTHandler  - Received a message of type CONNECT
7495 [pool-1-thread-1] ERROR ProtocolProcessor  - 
java.lang.RuntimeException: Can't find a ConnectionDescriptor for client null in cache {}
	at org.eclipse.moquette.spi.impl.ProtocolProcessor.sendPubAck(ProtocolProcessor.java:476)
	at org.eclipse.moquette.spi.impl.ProtocolProcessor.executePublish(ProtocolProcessor.java:324)
	at org.eclipse.moquette.spi.impl.ProtocolProcessor.processPublish(ProtocolProcessor.java:301)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:64)
	at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:173)
	at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:62)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
7498 [pool-1-thread-1] INFO  ProtocolProcessor  - PUBLISH from clientID <null> on topic </a/b/c> with QoS EXACTLY_ONCE
7501 [pool-1-thread-1] ERROR SimpleMessaging  - Serious error processing the message org.eclipse.moquette.proto.messages.PublishMessage@341cb737 for session [clientID: null]org.eclipse.moquette.server.netty.NettyChannel@72bcc5ea
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:66)
	at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:173)
	at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:62)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:64)
	... 6 more
Caused by: java.lang.NullPointerException
	at org.eclipse.moquette.spi.impl.ProtocolProcessor.sendPubRec(ProtocolProcessor.java:459)
	at org.eclipse.moquette.spi.impl.ProtocolProcessor.executePublish(ProtocolProcessor.java:330)
	at org.eclipse.moquette.spi.impl.ProtocolProcessor.processPublish(ProtocolProcessor.java:301)
	... 11 more
7517 [pool-1-thread-1] INFO  ProtocolProcessor  - cleaning old saved subscriptions for client <CocoaMQTT-20155>
7533 [pool-1-thread-1] INFO  ProtocolProcessor  - Create persistent session for clientID <CocoaMQTT-20155>
7573 [pool-1-thread-1] INFO  ProtocolProcessor  - Connected client ID <CocoaMQTT-20155> with clean session true
97566 [nioEventLoopGroup-3-1] INFO  NettyMQTTHandler  - Received a message of type PINGREQ
187576 [nioEventLoopGroup-3-1] INFO  NettyMQTTHandler  - Received a message of type PINGREQ
277573 [nioEventLoopGroup-3-1] INFO  NettyMQTTHandler  - Received a message of type PINGREQ
367575 [nioEventLoopGroup-3-1] INFO  NettyMQTTHandler  - Received a message of type PINGREQ
457575 [nioEventLoopGroup-3-1] INFO  NettyMQTTHandler  - Received a message of type PINGREQ
547579 [nioEventLoopGroup-3-1] INFO  NettyMQTTHandler  - Received a message of type PINGREQ

```

**Comment by erylee** [comment]
@pabloa, It seems you not specify clientId?  please check example: https://github.com/emqtt/CocoaMQTT/blob/master/CocoaMQTT/main.swift

**Comment by pabloa** [comment]
Hello

I edited the first comment to add the line with the client id. My code is basically a copy and paste of the example you pointed me. Subscriptions does not work win IOS 9.0 with Xcode 7.0.

Now I wrote this:

```javascript
    let mqtthost = "24.25.1.31"    
    let mqttCli = CocoaMQTTCli()
    let clientIdPid = "CocoaMQTT-" + String(NSProcessInfo().processIdentifier)
    let mqtt: CocoaMQTT = CocoaMQTT(clientId: clientIdPid, host: mqtthost, port: 1883)
    mqtt.willMessage = CocoaMQTTWill(topic: "/will", message: "dieout")
    mqtt.keepAlive = 90
    mqtt.delegate = mqttCli
    let connected = mqtt.connect()
    mqtt.subscribe("test", qos: CocoaMQTTQOS.QOS0)
    mqtt.publish("test", withString: "Qos0 Msg", qos: CocoaMQTTQOS.QOS0)
    mqtt.ping()
```

There is not connection with moquette server until the line with the subscribe method.
In that moment the server reports a packet error:

```text
195114 [nioEventLoopGroup-3-3] INFO  NettyMQTTHandler  - Received a message of type SUBSCRIBE
195115 [pool-1-thread-1] ERROR SimpleMessaging  - Serious error processing the message org.eclipse.moquette.proto.messages.SubscribeMessage@29b4261b for session [clientID: null]org.eclipse.moquette.server.netty.NettyChannel@23feadaa
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:66)
	at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:173)
	at org.eclipse.moquette.spi.impl.SimpleMessaging.onEvent(SimpleMessaging.java:62)
	at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.moquette.spi.impl.AnnotationSupport.dispatch(AnnotationSupport.java:64)
	... 6 more
Caused by: java.lang.NullPointerException
	at org.eclipse.moquette.spi.impl.ProtocolProcessor.processSubscribe(ProtocolProcessor.java:606)
	... 11 more
```

The broker is complaining about a null client id. But the value of the client id is 
```
clientIdPid	String	"CocoaMQTT-24722"	
```
It seems there is not connect message. No sure if that is ok. I guess it is.
Send and Ping messages are correctly sent and other clients get those messages.
But it does not work with subscriptions. The code above does not listen any message sent by other clients.

**Comment by erylee** [comment]
@pabloa, CocoaMQTT is asynchronous event-driven library. So you should not:
```
let connected = mqtt.connect()
mqtt.subscribe("test", qos: CocoaMQTTQOS.QOS0)
mqtt.publish("test", withString: "Qos0 Msg", qos: CocoaMQTTQOS.QOS0)
mqtt.ping()
```
You shoud subscribe/publish in the callback methods of the delegate:

```
class CocoaMQTTCli: CocoaMQTTDelegate {


    func mqtt(mqtt: CocoaMQTT, didConnect host: String, port: Int) {
        print("didConnect \(host):\(port)")
    }

    func mqtt(mqtt: CocoaMQTT, didConnectAck ack: CocoaMQTTConnAck) {
        print("didConnectAck \(ack.rawValue)")
        mqtt.subscribe("/a/b/c", qos: CocoaMQTTQOS.QOS1)
        mqtt.publish("/a/b/c", withString: "Qos0 Msg", qos: CocoaMQTTQOS.QOS0)
        mqtt.publish("/a/b/c", withString: "Qos1 Msg", qos: CocoaMQTTQOS.QOS1)
        mqtt.publish("/a/b/c", withString: "Qos2 Msg", qos: CocoaMQTTQOS.QOS2)
        mqtt.ping()
    }

```

**Comment by pabloa** [comment]
I confirm the connect packet is never sent.

It seems this method is never called:

```javascript
    public func socket(sock: GCDAsyncSocket!, didConnectToHost host: String!, port: UInt16) {
        #if DEBUG
        NSLog("CocoaMQTT: connected to \(host) : \(port)")
        #endif
        connState = CocoaMQTTConnState.CONNECTED
        let frame = CocoaMQTTFrameConnect(client: self)
        send(frame)
        reader!.start()
        delegate?.mqtt(self, didConnect: host, port: Int(port))
    }
```

Is it possible it is a bug?

**Comment by pabloa** [comment]
Thanks for your answer. I am modifying my code so it will do nothing except in the called function
```
func mqtt(mqtt: CocoaMQTT, didConnectAck ack: CocoaMQTTConnAck) {
```

**Comment by pabloa** [comment]
It works sometimes. Sometimes it connects and stays connected. Other times it connects and it immediately disconnects by calling this method:
```javascript
    public func socketDidDisconnect(sock: GCDAsyncSocket!, withError err: NSError!)
```
No sure why the connection is closed. The system / anything else calls it.

**Comment by CrazyWisdom** [comment]
@pabloa , I tested six times, did not find the problem you said. One time I used Ctr+c terminated the moquette server and  starts again, server log has the following error(But, when I executed: rm bin/moquette_store.mapdb*, and starts the server again, It works fine):
```
Caused by: java.lang.RuntimeException: Can't find a ConnectionDescriptor for client <CocoaMQTT-55327> in cache <{CocoaMQTT-55501=ConnectionDescriptor{m_clientID=CocoaMQTT-55501, m_cleanSession=true}}>
	at org.eclipse.moquette.spi.impl.ProtocolProcessor.sendPublish(ProtocolProcessor.java:439)
	at org.eclipse.moquette.spi.impl.ProtocolProcessor.forward2Subscribers(ProtocolProcessor.java:388)
	at org.eclipse.moquette.spi.impl.ProtocolProcessor.executePublish(ProtocolProcessor.java:317)
	at org.eclipse.moquette.spi.impl.ProtocolProcessor.processPublish(ProtocolProcessor.java:301)
	... 11 more
6757 [pool-1-thread-1] INFO  ProtocolProcessor  - PUBLISH from clientID <CocoaMQTT-55501> on topic </a/b/c> with QoS LEAST_ONE
6775 [pool-1-thread-1] INFO  ProtocolProcessor  - send publish message to <CocoaMQTT-55327> on topic </a/b/c>
6776 [pool-1-thread-1] ERROR SimpleMessaging  - Serious error processing the message org.eclipse.moquette.proto.messages.PublishMessage@20260f36 for session [clientID: CocoaMQTT-55501]org.eclipse.moquette.server.netty.NettyChannel@7b05e839
```

Other times , It works fine.
server log:
```
5645 [pool-1-thread-1] INFO  ProtocolProcessor  - cleaning old saved subscriptions for client <CocoaMQTT-55574>
5660 [pool-1-thread-1] INFO  ProtocolProcessor  - Create persistent session for clientID <CocoaMQTT-55574>
5696 [pool-1-thread-1] INFO  ProtocolProcessor  - Connected client ID <CocoaMQTT-55574> with clean session true
5698 [pool-1-thread-1] INFO  ProtocolProcessor  - <CocoaMQTT-55574> subscribed to topic </a/b/c> with QoS 1 - LEAST_ONE
5715 [pool-1-thread-1] INFO  ProtocolProcessor  - PUBLISH from clientID <CocoaMQTT-55574> on topic </a/b/c> with QoS MOST_ONE
5717 [pool-1-thread-1] INFO  ProtocolProcessor  - send publish message to <CocoaMQTT-55574> on topic </a/b/c>
5718 [pool-1-thread-1] INFO  ProtocolProcessor  - PUBLISH from clientID <CocoaMQTT-55574> on topic </a/b/c> with QoS LEAST_ONE
5764 [pool-1-thread-1] INFO  ProtocolProcessor  - send publish message to <CocoaMQTT-55574> on topic </a/b/c>
5787 [pool-1-thread-1] INFO  ProtocolProcessor  - PUBLISH from clientID <CocoaMQTT-55574> on topic </a/b/c> with QoS EXACTLY_ONCE
5791 [pool-1-thread-1] INFO  ProtocolProcessor  - send publish message to <CocoaMQTT-55574> on topic </a/b/c>
36648 [pool-1-thread-1] INFO  ProtocolProcessor  - Lost connection with client <CocoaMQTT-55574>
```

Xcode log:
```
Hello, CocoaMQTT!
didConnect 127.0.0.1:1883
didConnectAck 0
didPublishMessage to /a/b/c
didPing
Delegate: didReceivePong
didSubscribeTopic to /a/b/c
didReceivedMessage with id 0
message.topic: /a/b/c
message.payload: Optional("Qos0 Msg")
didReceivedMessage with id 1
message.topic: /a/b/c
message.payload: Optional("Qos1 Msg")
didPublishMessage to /a/b/c
didReceivedMessage with id 2
message.topic: /a/b/c
message.payload: Optional("Qos2 Msg")
didPing
Delegate: didReceivePong
```
I ran the CocoaMQTT project, Only modified two lines in main.swift
```
//mqtt.username = "test"
//mqtt.password = "public"
```
